export enum HEADER_J_DEBITS_JP {
    USER = 'ご利用者',
    TRANSFERRED_DATE = 'お振替日',
    USAGE_OR_DESTINATION = 'ご利用先など',
    TRANSFERRED_AMOUNT_IN_JPY = 'お振替金額（￥）',
    DESCRIPTION = '摘要',
    AUTHORIZATION_CODE = '承認番号'
}

export enum HEADER_NORMALIZE_EN {
    USER = 'USER',
    TRANSFERRED_DATE = 'TRANSFERRED_DATE',
    USAGE_OR_DESTINATION = 'USAGE_OR_DESTINATION',
    TRANSFERRED_AMOUNT_IN_JPY = 'TRANSFERRED_AMOUNT_IN_JPY',
    DESCRIPTION = 'DESCRIPTION',
    AUTHORIZATION_CODE = 'AUTHORIZATION_CODE'
}